#cloud-config

hostname: {{VM_NAME}}
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAvcaJcWLvj8sr73OOnwYB4HE604StBQdRtkcnRyGBGV2GRPvk+lqw88wsFalpWYHgGydrrvakFT4vru2A8N53/KYVG3DUAzUhcN/RuC4DDlu5QC93jKEoln1HFVD7+KdRtzWOEk1j/ID1zCYnyUbuI/OYFCFItxa9NKPf4qGkpHVBfdRwisML6YgQMxFOWlN3CyxNMouUe3vbzW9gblzHUr2pQQXz8UR3QPY0VjpEG12uCCi3iv+gZMFj2VzL/HeN0d8ANfdsFnLN5p/gDvy+Sg2og1nJ723aK/5RjDITUWBrxgw3gdDNhWhGcjFIS3yfjs7fHl49MjY6RM6QH56BEw==
coreos:
  units:
    -name: static.network
      command: start
      content: |
        [Match]
        Name=eth0

        [Network]
        Address=192.168.245.0{{VM_NUMBER_00}}/24
        DNS=192.168.240.1
        Gateway=192.168.240.1
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: docker.service
      command: start
  etcd:
    name: {{VM_NAME}}
    discovery: {{ETCD_DISCOVERY_TOKEN}}
  fleet:
    metadata: region=hyperv-net1
  update:
    reboot-strategy: etcd-lock
    group: alpha
manage_etc_hosts: localhost